@extends('layouts.app')

@section('content')
<section>
    <div class="ui grid container stackable">
        <div class="sixteen wide column">
            <h1>Privacy Policy</h1>
            <hr>
            <div class="content">
                <p>This privacy policy sets out the conditions under which occurs the use of services related to the portal www.moreflirts.com. By accessing this site, you acknowledge having read and understood the general conditions of contract and automatically accept our privacy policy. If you do not agree to these terms please do not access the site.</p>
                <h3>1. Collection of Personal Information</h3>
                <p>Upon enrollment, or to purchase a subscription, we ask you to provide some personal information. Remember that certain information, or content-called “sensitive”, provided by the customers as optional may, under the responsibility of the affected user, reveal his ethnic origin, political opinion, philosophical or religious, nationality, and / or sexual orientation. Typing this type of information, all optional, the user agrees to make them public; therefore expressly agrees that our dating service and its selected partners use this data through it’s profile. The data collected on our site, identified by an asterisk is mandatory. Your personal information will be used by www.moreflirts.com. respecting the principles of protection of privacy established by Legislative Decree n. 196 of 30 June 2003 (as amended) and other applicable regulations. For this treatment the law asks for the consent of the user, which must provide in advance some information.<br>
                    The Code’s guidelines apply:<br>
                    a) “processing” means any operation or set of operations, carried out without the aid of electronic instruments, concerning the collection, recording, organization, storage, consultation,processing, modification, selection, extraction, comparison, use, interconnection, blocking, communication, dissemination, erasure and destruction of data, even if not registered in a bank data;<br>
                    b) “personal data”, any information relating to an individual, legal person, corporation or association, identified or identifiable, even indirectly, by reference to any other information, including a personal identification number;<br>
                    c) “identification data”, personal data that allows direct identification;<br>
                    d) “sensitive data”, personal data allowing the disclosure of racial or ethnic origin, religious, philosophical or other beliefs,political opinions, membership of parties, unions, associations or organizations of religious, philosophical, political or trade union membership and personal data disclosing health and sex life.This information concerns the personal data sent by the user during registration, as well as those derived from visits and navigation on our website and then submitted by the user to the service activation offered within the Portal. In Law Enforcement Freedom of Information (*), each user can access or request access to information relating him, to edit, delete or prohibit any use by our society. (*) “And Freedoms” n ° 78-17 of January 6, 1978 as amended by Law 2004-801 of 6 August 2004 integral in French law Directive 95/46 / EC of 24 October 1995 on the protection of personal data and privacy within the European Union and the law on “confidence in the digital economy” n ° 2004-575 of 21 June 2004 (Article L. 04.01.33 amended by code of Post and Telecommunications and article L . 121-20-5 of the new Consumer Code) integrating into French law Directive 2000/31 / EC of 8 June 2000 on electronic commerce and Directive 2002/58 / EC of 12 July 2002 on the protection of personal data and privacy in electronic communications.</p>
                <h3>2. Nature and use of the information collected</h3>
                <p>2.1 Mandatory and optional user-supplied personal data requested are divided into two categories: mandatory and optional, as indicated in the procedure of registration and request activation of services offered.<br>
                    In our online registration, we ask you to provide certain mandatory information such as name, email address, gender, date of birth, location, as well as other optional personal data. This data is accessible at all times and can be corrected or updated by going to the “Your Profile”. The user must choose theusername and password. The nickname and password will then be the access codes of the user. The supply of mandatory data and its processing for the purposes mentioned above are strictly “a must “ to the services. If the user refuses to provide such data or any refusal to allow their treatment will make it impossible to use the services offered by the portal.<br>
                    www.moreflirts.com gives users a reserved area where at your discretion, you can add more details about you, post photos, videos, descriptions, text and other content in general. If you volunteer this kind of data, you explicitly consent to their use by us in accordance with this Privacy Policy Note. The personal information of our users are used to our internal, statistically analyze site usage, to verify compliance with the regulations, to improve our content and services and to customize the content and style of the site to your needs. We may also use your personal information to send you e-mails about information that could be of interest. You can choose to receive e-mails from us regarding new notifications and messages, visit of another user or user presentation corresponding to their search criteria to take advantage and make full use of our online dating service. The user can choose to disable this feature through the “Settings” page. The user does not need to close their accounts in order not to receive more mail from us.<br>
                    2.2 Information collected by the computer system<br>
                    When a user accesses the site automatically detects the version of the browser used (Internet Explorer, Firefox, Google Chrome, etc.), The version of the operating system (Windows, Linux, etc.) and the IP address awarded for the internet connection. Moreover, www.moreflirts.com uses cookies, designed to store information to identify the Member while browsing the site, to avoid manual entry in each new page. These cookies do not contain your personal details, which can be prevented by changing your browser’s options ,used for navigation on the Internet.</p>
                <h3>
                    <p>According to the GDPR requirements regarding the processing of personal data and the free circulation of such data, MoreFlirts.com is necessary to manage, in a secure way and only for specific purposes, the personal data provided by you.</p>
                    <p>The purpose of data collection is:</p>
                    <ol>
                        <li>To send e-mail notifications when a user sends a message, she is not online</li>
                        <li>To research the market, monitor and follow visitor behavior</li>
                        <li>To send occasional newsletters with offers and promotions</li>
                    </ol>
                    <p>Reading the document you acknowledge that you are guaranteed the rights provided by law, namely the right to information, access to data, the right to action, the right to oppose, the right not to be subjected to an individual decision, the right to face justice in case of violation of the rights related to the processing of personal data and the free circulation of such data.</p>
                    <p>Upon request sent by e-mail: contact@moreflirts.com, you can request, free of charge, for confirming that the personal data is I have not been processed and you can exercise the right to have the data, as appropriate:</p>
                    <ol>
                        <li>rectification, updating, blocking or deletion of data whose processing is not in compliance with the law to protect individuals with regard to the processing of personal data and the free movement of such data, especially incomplete or inaccurate data;</li>
                        <li>the transformation into anonymous data of data whose processing is not in compliance with the law on the protection of individuals with regard to the processing of personal data and the free movement of such data;</li>
                        <li>notification to third parties, to whom the data have been disclosed, if it is not proved impossible or involves a disproportionate effort towards the legitimate interest that could be damaged.</li>
                    </ol>
                    <p>Also MoreFlirts.com can provide the personal data of the acquirer to other companies that are in a partnership relationship, but only in the form of a confidentiality commitment from them and only for the purposes referred to in paragraph 1.2., Which guarantees that these data they are kept safe and that the provision of personal data is required by law, as follows: courier service providers, marketing providers, payment / bank providers, telemarketing or other services provided by companies with whom we can develop programs common marketing for our goods and services.</p>
                    3. Privacy
                </h3>
                <p>The processing of personal data and sensitive data processed in a manual or computerized manner, is strictly related to the purposes and, in any case, in order to ensure the security and confidentiality of data. All data collected is held in archives and databases located within the premises of our Company. To maintain a community in order, www.moreflirts.com works closely with all the requests made by law enforcement agencies or third parties in relation to the respect of others’ rights, including intellectual property. We reserve the right to disclose your personal information if requested by the competent authorities and if we believe that the above disclosure is necessary to protect our rights and / or to comply with any requirements related to legal proceedings in which is involved our site.</p>
                <h3>4. Closing the account</h3>
                <p>4.1 Cancellation by the user<br>
                    You may at any time choose for the cancellation of the data entered by accessing your personal area and eliminating your account.After the cancellation the porta stores only the text messages included in the forum, which will be considered published by an anonymous user. Upon the cancellation the nickname is immediately made available for registration by other users.<br>
                    4.2 Cancellation by www.moreflirts.com.<br>
                    www.moreflirts.com reserves the right to delete the contents of the restricted area of ​​a user, to block the use of certain words or terminologies in both chat and emails, to block use in case of abuse and to put under preventative validation pictures and descriptions inserted without notice. Any informationis subject to validation by the moderators. It i strictly forbidden to publish pictures or other material with pornographic character or that depicts minors in general. Any user who violates this rule may be subjected to the cancellation of the account without notice. The closure of the account does not give right to any refund.</p>
                <h3>5. Changes to this Privacy Policy</h3>
                <p>If we decide to change our privacy policy or the use of e-mail, we will put the changes in this document, and we will tell you in the manner and in places we deem appropriate to you. We reserve the right to modify this privacy statement at any time; so you should check it frequently. If we make material changes to this policy, we will notify you here, by e-mail or through a notice on our homepage.</p>
                <h3>6. Further information</h3>
                <p>You can contact the team www.moreflirts.com by e-mail with any questions, at contact@moreflirts.com.<br>
                    For questions concerning the right of access and rectification and, more generally, privacy, it is<br>
                    please write to contact@moreflirts.com</p>
            </div>
        </div>
    </div>
</section>
@endsection