@extends('layouts.app')

@section('content')
<section>
    <div class="ui grid container stackable">
        <div class="sixteen wide column">
            <h1>Terms and conditions</h1>
            <hr>
            <div class="content">
                <h3>1. PRESENTATION OF THE PORTAL</h3>
                <p>www.moreflirts.com is an online dating site and publication of short ads. By entering the portal you will be able to exchange written messages, videochat live with other users and much more. The site is reserved for mature adults. All registered users and the people in your photos are 18 years of age or older .Some features of the site are accessible for free, others are paid for by Members, who pay for subscription. The user is informed that in accordance with Article 32 of the Data Protection Act and Freedom of 6 January 1978, as amended, the information collected is necessary and is intended to GLAMSIM as responsible for their management ,for the management of customer files and potential customers, the management of subscribers, the control of the relationship between customers and potential customers, the management and control of commercial and promotional operations. The user can exercise the right of access, rectification and assistance that allows, if necessary, to correct, complete, update, block or delete the personal data if it is inaccurate, incomplete, unclear, no longer valid or truthful whose collection, use, communication or storage is prohibited. The user also has the right to object to the processing of personal data for legitimate reasons and the right to object if they are used for commercial research.</p>
                <h3>2.REFUND POLICY</h3>
                <p>The member who bought a paid service is entitled to exercise his right of withdrawal within 14 working days from the date of purchase, without penalty and without cause. In any case after the purchase of an package the member who uses the chat or the webcam service, can no longer exercise the right to refund.</p>
                <h3>3. Use of our portal</h3>
                <p>By becoming an user you agree to follow and to respect the conditions use set out below, as well as having confirmed his email address. If the user does not read or if you do not accept the terms and conditions of use,the user can not join the dating site.<br>
                    While using the services, the member agrees to:<br>
                    1) To use www.moreflirts.com exclusively for personal purposes only excluding any professional or commercial use (for example, but not limited to, looking for customers, promotions, soliciting or prostitution)<br>
                    2) Do not use expressions or publish content that in any form violates property rights to a third party or that is obscene, vulgar, violent or inciting violence, racial or xenophobic, defamatory, abusive, and generally content that is contrary to the laws and regulations in force, personal rights or morality. Photos, videos and any other information exchanged or published on our site must be decent and refer exclusively to the user, or in the case of third party, the user will have to be sure you have received permission.<br>
                    3) Do not post, spread information or content that has the effect of diminishing, disorganizing or obstructing the normal use of services, or interrupting and / or slowing down normal circulation communication between members through services such as applications, viruses, sending messages in bulk (spam), etc..<br>
                    www.moreflirts.com reserves the right to delete messages sent in bulk of an Member in order to ensure the quality of the service for and from other Members.<br>
                    4) Do not post phone numbers or email addresses via message, the exchange of such personal data may be made directly between users chatting. The sending of phone numbers or email in a different way from that expected, will be ‘interpreted as “spam”. Spam is automatically removed by software without human intervention so it will be impossible to recover any sent information.<br>
                    5) Do not indicate, publish, suggest nor spread in any form, links to websites operated by third parties that are illegal in character, or compete with www.moreflirts.com<br>
                    6) Do not collect or store personal data of other users. If you do not meet these requirements, we will be forced to implement the sanctions from warnings to the cancellation of the profile without prior notice and without refund.<br>
                    If you begin to have contact with the people you want to meet you act with caution:<br>
                    – Choose a public place for the first meeting: bar, cinema, museum …<br>
                    – Inform someone of the meeting place and time and in case of need bring a friend along.<br>
                    – Do not give out personal information before you know the person with whom you have contact through our website.<br>
                    – Do not give to anyone you’re bank statements.<br>
                    – Be wary of the people asking “help” in money: never accept. In case of fraud we decline any liability. If you have some doubt about the honesty of a member or if you receives indecent proposals<br>
                    you can report someone by clicking on the link at the bottom of each profile. You remain anonymous to the person and we’ll delete the profile if you think that the request is justified.</p>
                <h3>4.Protection of personal data</h3>
                <p>www.moreflirts.com respects the Italian and European standards on the security and privacy of sensitive data of their members. Some information, comments or content (photographs) that the member optionally provides may possibly, under the responsibility of the member concerned, reveal the ethnic origin, nationality, religion and / or sexual orientation of the Member. By providing such information, all optional, the concerned member consequently, expressly consents to the processing of this mentioned “sensitive” by www.moreflirts.com. www.moreflirts.com assumes sole responsibility. The personal data given by the customer will be collected, processed, stored and used within the services offered as per contract. Personal data is the data that provides information on personal characteristics or objective of a natural person. eg. age, gender, postal code, no. phone, the analysis of the test results for inclusion in the service photos and e-mail addresses.<br>
                    In case you need to process an order of a service subject to costs, then you’re going to take up the customer’s name, his address and his bank or credit card details. The info gathered about you by www.moreflirts.com and our services are used to offer you our services. All precautions have been taken on our databases to archive your information in a protected environment. Some of our employees have access to personal information only when necessary.<br>
                    Personal information provided during registration which does not comprise your personal ad of his presentation will not be accessible by third parties, transferred, sold or exchanged, except in<br>
                    cases mentioned below and subject to your prior information and consent of the member concerned or if the Member has expressed his opposition about. The customer has the right to revoke<br>
                    immediately or in the future such authorization or request the correction of personal data stored in the www.moreflirts.com.<br>
                    The client also authorizes the www.moreflirts.com to disclose personal data of his profile to external operators for the following clearly defined purposes:<br>
                    a) to send the name and account of www.moreflirts.com (e-mail, newsletters)<br>
                    b) to carry out other media elements www.moreflirts.com profiles of customers;<br>
                    c) to perform payments in the name and on behalf of www.moreflirts.com;<br>
                    d) preventing and combating the misuse of the service;<br>
                    www.moreflirts.com receives and automatically records some information (log) from the browser used by the visitors, the IP address, the cookie information and the pages requested by the visitors. www.moreflirts.com uses all<br>
                    The information collected using automatic systems for three general purposes: to customize the advertising and content to visitors, to respond in the best way to the requests of<br>
                    certain services, and ultimately make more effective and efficient services to its users.<br>
                    Consequently, the Member explicitly authorizes www.moreflirts.com to reproduce and broadcast the info available in your personal ad, search criteria and in his (personal information, description, images, videos, etc.) On www.moreflirts.com, in whole or in part (on the site, on the web, by email) and / or on any media and means of communication, in particular audiovisual communication (press, radio, broadcast, digital, cable or satellite) or electronic communication (email, Internet), worldwide and for the period of validity of these Terms of Use between the Member and www.moreflirts.com.<br>
                    Each user can log in to the site with his Nickname and Password, direct access to all the information about you to edit or delete or block the use of www.moreflirts.com. In case of modification or deletion of information is comprised of, in the search criteria or presentation user, modification or elimination will only take effect from the next update or subsequent editing communication media (print, audiovisual or electronic) containing info about your search criteria.</p>
                <h3>5. Liability and Warranty</h3>
                <p>The data provided by you and published on the site must be accurate and conform to reality. The consequences of disclosing information on the life of the user and / or of other users are under the sole responsibility of the user.<br>
                    And ‘the user who takes the initiative to divulge and spread on www.moreflirts.com personal data, information, text, content and images. Therefore, you waive any action against www.moreflirts.com, in particular for a possible violation of the right to the image, to his honor and reputation, the intimacy of his private life, resulting from spread or disclosure of information concerning him, because the user has given his prior, free and express consent to such revelation through his registration to the site and in application of these terms.<br>
                    The member must have the skills, equipment and software required to use the Internet or, if necessary, the internet and telephone services, and recognizes that the characteristics and the constraints of the internet,help ensure the protection, availability and integrity of data transmissions on the Internet. www.moreflirts.com can not guarantee that the service will meet your needs, you will be provided without interruption, timely, secure or error-free. For any failure of the service caused by events outside our control, including but not limited to, strikes, closures, explosions or accidents, fire or brownout, etc. we decline all responsibility.</p>
                <h3>6. Termination</h3>
                <p>The termination of registration is effective immediately. The interruption will include the complete deletion of the profile as well as messages and all other personal information in our possession. Important: after deleting the profile, you can no longer make any claim. If you have a subscription, you must first disable the subscription and then delete the account.</p>
                <h3>7. Amendments to the terms and conditions of service</h3>
                <p>www.moreflirts.com reserves the right to change these terms from time to time in its sole and absolute discretion. Every registered user will be informed, through the website or by e-mail, of the changes made and will be invited to read and accept the new conditions of use.The users are requested to read these terms regularly to ensure that you have knowledge and understanding the latest version. The continued use of the services on the site implies explicit acceptance of the new changes by the user. If the user does not accept the new conditions, the latter must notify his refusal by the immediate cancellation of its registration and the consequent termination of the use of the site.</p>
                <h3>8. Governing Law</h3>
                <p>These terms of use are governed, interpreted and applied in accordance with Italian law and in case of disputes about the meaning of an term and provision of these conditions of use will be in the Italian language. Subject to the mandatory public dispositions concerning jurisdiction, the court of Italy will be the only jurisdiction in any dispute relating to these dispositions, including, but not limited to, their validity, interpretation, execution and / or resolution and its consequences.</p>
                <h3>9. Contact:</h3>
                <p>contact@moreflirts.com</p>
                <p>Company TWO DATING SRL – CUI 41132017, ISAIIA, Iasi, Romania</p>
            </div>
        </div>
    </div>
</section>
@endsection